[firebase]
type = "service_account"
project_id = "smarthid-32dfc"
private_key_id = "30298c40df2f1c439463a3232a5b5013922aa93e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQDG3VmArVo75xm+
8qMjd+gBJo1aGaaGpfw7/tgORDZKpCB689oMrvYu49f9sNrKM6BL5tlxGjbejsvB
cn9RVafQ8dX0vf04ENnpNR31/73paqBMAB+pwXmxnYWfJ1D4jaq3FOgn7z9/puR5
Gtv1n39cqVl4aSPBYWnlctj7zxEFUQkNvIbn052V3mQynCPU17GQX9NzYHq66esR
6dlFhvOAh+qUmU+4Tq7yXI4Ue+Ay/1ueRQNjqJ53VsyQfwtuXMiNmTuqKi+uxmaf
bqjC2Mcj7zbhReqT1un2JXvOSwG4Azknx6Fr9P3WU5jj0O3O99yIJnnUkQd7109r
4CmrBkzfAgMBAAECgf9+OwMVKvScEZXGHz5uxS3/jPksuBt8XOA/NQTwCVxtBMGZ
SjCe3HBoUzhHUHuQ3jRh+acMpBcwLnQn1wX6GuTrPJcTQ4X4kLnBznW2MR/bilM1
6t4uYyFcHSE0ZUCAhWxXym2S68rivI1KUkJNJ3Ew4E5qoFKR7cPKYZxaOpYTSL1E
G+EFImN3OctP8BFclI3hsKRGmv35OvGln0sVP4ITDuNsMGvtsD+wzTZSzrmf9U6z
wgDUVKbNXrldNGZYYDYzOCU51T8yOTN5L8gyi4j87RM4/YLNpoqJjGhSRlc7aPyV
suKK5yj7mMFs2lRLF1vRe9PQItnIksGonBxyHL0CgYEA97pn8aUmwvOg5bNJjg+p
5NR8dwVS5Cy2SnkObxsK6A5OdNu3J3Z69HtcedloJg8yamqIXgSocjTi6LTJlArO
ZpO+BFcLMn/QKwCj49QHmayh/WTRHO+6UJhFptIoVI8mDYPo6CggYRTG2fjEkRZv
Hb0PjedajNKXZC7AkZVEhd0CgYEAzYFBcy+/5xRGiXcUi9ijTGZuvvH+/NS+ZCNi
/e3EXm74I9UeRG3Dsf2dxUO16kuvHdkMqr9cXOMboIkdBquW9SemryPkvh9BObwd
ExjWUzkilvy/RB68vuFHG0tnvOcXHXhBO6RDW467ob0w+5q6IWW5vo+I7cpz1/gE
YzjZ5+sCgYBaLchC5fzLQQbUN0TSaw9MlrFMXmrDVydwysqfVXfN689RqN3uhqnR
r8qFLMhF+og+xtMnboinMmtbjNxIgPqLysKEL++KjY6I6O3ANOIjZf1+EaIx526q
ghPw21YFGisfBmLViC3pSTfuByn/Kux+JeGwpYSH+O1VcdN166GLHQKBgFi8xpFB
fiD/DVJQfCvC2Qildo63Gj78clX1PcqeP9vzGO0IGrC7oPQbqmPC0CuikLRXw/N6
/BwT6RsR+dmmgGHNxFj+K8i44EZY50kWwX1gP4JpEwIML75Qso6jqeDU/JM6GRjy
3i8L3BOECUGr11GShnk1q4/aitkn/GUH6HgPAoGBAN4zKn2TrLCK546irUfi7MAn
4jJ1Ie+4jIIcYOyyaslEAn1o+utBLZzq6xa2zTROfNCFz+icDdpPtZj4ir5l5wo4
YIpULX2SNaCBycCWXnNPka5KJyL6Lwe2TzM2qCZPuerWPsgobLCfHpDFYq18KPOA
yzGp6oDz6yfTQnST0XHT
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@smarthid-32dfc.iam.gserviceaccount.com"
client_id = "107382354490894015313"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40smarthid-32dfc.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
